# Generated by Django 4.1.2 on 2022-10-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='value',
            field=models.IntegerField(),
        ),
    ]
